$('#s_wrap').fadeOut(250)
$('#s_top_wrap').fadeOut(250)
$('#s-top-left').fadeOut(250)
$('#u1').fadeOut(250)
$('#s-hotsearch-wrapper').fadeOut(250)
$('#bottom_layer').fadeOut(250)
$('#s_side_wrapper').fadeOut(250)
$('#head').css('min-height', 'initial')
